version: "3"

services:
  site:
    image: dougboutwell/redfeedbluefeed-site:latest
    build: .
    restart: "no"
    environment:
      - NODE_ENV=dev
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
    restart: unless-stopped
